const BurgerActionTypes = {
  ADD_INGREDIENT: "ADD_INGREDIENT",
  REMOVE_INGREDIENT: "REMOVE_INGREDIENT",
  SET_BURGER_NAME: "SET_BURGER_NAME",
  CLEAR_INGS: "CLEAR_INGS",
};

const FeedBackActionTypes = {
  SHOW_ALERT: "SHOW_ALERT",
  HIDE_ALERT: "HIDE_ALERT",
};

const CartActionTypes = {
  LOAD_CART: "LOAD_CART",
  SET_ISUPDATED: "SET_ISUPDATED",
  ADD_CART: "ADD_CART",
  REMOVE_CART: "REMOVE_CART",
  REMOVE_CARTS: "REMOVE_CARTS",
  UPDATE_CART: "UPDATE_CART",
};

const AppActionTypes = {
  OPEN_MOBILE_DRAWER: "OPEN_MOBILE_DRAWER",
  CLOSE_MOBILE_DRAWER: "CLOSE_MOBILE_DRAWER",
};

export {
  BurgerActionTypes,
  FeedBackActionTypes,
  CartActionTypes,
  AppActionTypes,
};
